type = "card"
title = "Internship"
description = "About my Internship."

[[items]]
title = "BeingBeyond"
subtitle = "Reaserch Intern"
date = "2025-2026"
content = "Large Modals and Dexterous Manipulation"
